### ISSUE TITLE
Setting up webpack

### ISSUE THREAD

**Issue by CasiOo** [wesharehoodies/todo-react#3]
Webpack is our chosen frontend build-system.
Following tasks should be handled by Webpack:
- Bundle client js
- Output client js in dist/build directory
- Requiring bundled/unbundled SASS files. Requires a loader https://github.com/jtangelder/sass-loader
- Watch client files for changes

@arreche said he'll take a look at it :)

**Comment by arreche** [comment]
Setup webpack for both front and back sides is bit tricky at the moment.

http://jlongster.com/Backend-Apps-with-Webpack--Part-II

So I'm going to focus on setup it in the front.

**Comment by CasiOo** [comment]
I liked how webpack was setup here: https://medium.com/@dabit3/beginner-s-guide-to-webpack-b1f1a3638460
At the bottom, there is an example setting up webpack for react and es6 (don't like the .es6 extension he's using haha)

**Comment by arreche** [comment]
I'm following this cookbook

https://christianalfoni.github.io/react-webpack-cookbook/

**Comment by arreche** [comment]
Closed because #7
